### ISSUE TITLE
Removing price information or not

### ISSUE THREAD

**Issue by onurklngc** [bounswe/bounswe2017group8#30]
Dear Rahmetullah,
Considering customer feedback given below, shall we remove the price information from "Registered User Home Page" mock-ups?

1.3.1: Price is not necessary. We don't want this project to be something like Biletix.

Sincerely,
Onur

**Comment by rvarol** [comment]
I have modified the mock-up so that it is clear that the price information may be not available and that piece of information is an optional information that may or may not be provided by the creator of the page. I think this is the best way go about for now but we may update once we have cleared this point with the customer.
